apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
    env: stage
spec:
  replica:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name:
        image:
        port:
        - containerPort:
        envFrom:
        - configMapRef:
            name: myapp-config
        env:
         - name: DB_USERNAME
           valueFrom:
             secretKeyRef:
               name: myapp-secret
               key: DB_USERNAME
        volumeMounts:
        - name: myapp-storage
          mountPath: /data
    volumes:
      - name: myapp-storage
        persistentVolumeClaim:
          claimName: myapp-pvc
