apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app.name}}
  labels:
    app: {{.Values.app.name}}
    env: {{.Values.app.env}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      containers:
      - name: {{.Values.app.name}}
        image: {{.Values.image.repository}}:{{.Values.image.tag}}
        ports:
        - containerPort: {{.Values.service.port}}
        envFrom:
        - configMapRef:
            name: {{.Values.configmap.name}}
        env:
         - name: {{Values.secret.dbUsernameKey}}
           valueFrom:
             secretKeyRef:
               name: {{Values.secret.name}}
               key: {{Values.secret.dbUsernameKey}}
        volumeMounts:
        - name: {{Values.volume.name}}
          mountPath: {{Values.volume.mountPath}}
    volumes:
      - name: {{Values.volume.name}}
        persistentVolumeClaim:
          claimName: {{Values.volume.pvcName}}
          
